# Generated by Django 4.2.7 on 2023-12-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='surname',
        ),
    ]
