# Generated by Django 4.2.7 on 2023-12-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_recipeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='slug'),
        ),
    ]
