# Generated by Django 4.2.7 on 2023-12-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='view_count'),
        ),
    ]
